export const dummyData = [
  "Added Avatar component and display in header",
  "Added bulk import of Dones",
  "Added logos to site",
  "Added routing to the app",
  "Adjudicated the dispute between databases and user interfaces for BAO.",
  "Adjusted custom query & add to inlmexico",
  "Ameliorated the system for collecting data for WIAAM.",
  "Amorphized 34 hectopascals of atmospheric pressure",
  "Amplified the phase transition of 9 dodecahedral polyhedrons",
  "Angularized contactForm",
  "Answered CEPPS linked table questions",
  "Answered how do admin divisions work?",
  "Answered questions about ARP with no data question",
  "Answered reporting status target upload & partner access questions",
  "Answered target publication question",
  "Arranged a liaison with Advance Nutrition to streamline their reporting process.",
  "Assembled a team of algorithms to conquer the monolithic task of data aggregation",
  "Battled the dragon of complex systems architecture",
  "Brewed a pot of fresh, piping hot code",
  "Brokered a data exchange agreement between Lab and their partners",
  "Built a bridge of data connectivity between Feed the Children and their partners",
  "Built a new data module for JSI to enable their reporting on youth engagement",
  "Built Accenture site",
  "Canonically commuted 14 non commutative geometries",
  "Carved out a path of optimization for NDI's M&E system.",
  "Cast a spell of organization on Mercy Corps' database structure.",
  "Catalyzed the reaction of 14 tetrahedral fullerenes",
  "Celebrated a victory over the bug that was hindering JSI's project tracking.",
  "Co-created a comprehensive data strategy with IBTI to boost their impact measurement",
  "Cold calls and working on connecting prospects from '22",
  "Collaborated with IESC to streamline their M&E processes through data automation",
  "Composed a lyrical solution to a stubborn coding issue",
  "Conceived a vision of data clarity with Counterpart.",
  "Conceived a visionary approach to data privacy for shejehSalam",
  "Concluded a peace treaty between data and analysis with ACDIVOCA.",
  "Concocted a potion of quality control for IFAW.",
  "Conducted a site visit with WINROCK to understand their current needs and discuss potential services.",
  "Conducted a workshop with 2SCALE on improving their monitoring and evaluation processes.",
  "Configured the automatic data syncing for ChildFund to streamline their data collection process",
  "Conquered the Hydra of nested queries for Advancing Nutrition",
  "Conquered the Minotaur of data analytics with Open Doors.",
  "Conquered the unruly beast of the cross-browser compatibility issue",
  "Constructed a towering monument of data accuracy for Green Climate Fund",
  "Created a symphony of elegant, functional code",
  "Created blog/model for INL and other narratives",
  "Created custom data visualization tools",
  "Created custom function for INL reports",
  "Created custom queries for data analysis",
  "Created custom queries for INL data",
  "Created reports for data analysis",
  "Created standard process for undeleting subnational",
  "Cultivated a lush garden of seamless user experiences",
  "Cut the Gordian knot of data integration for CRR",
  "Danced the tango with the terse but elegant Python language",
  "De-orbited 25 zettabytes of subspace anomalies",
  "Decapitated 25 zettabytes of information",
  "Deciphered the mysteries of cryptic code and fixed a reporting issue for Cordaid",
  "Deconstructed 56 semi-autonomous quasicrystals",
  "Decontaminated 15 gigabytes of outdated code for INL.",
  "Defeated the cyclopean demon of data inaccuracies for EPISCOPAL RELIEF",
  "Dehydrated 29 deciliters of dihydrogen oxide",
  "Delivered a coup de grace to the massive software bug for LMH.",
  "Delved into the depths of data analysis for MCC to uncover new insights",
  "Deployed a dynamic data dashboard for IAVDI to improve their decision-making",
  "Deployed a new API integration for Plan to improve data connectivity",
  "Deployed this goofy thing",
  "Dereferenced 12 transfinite topological spaces",
  "Designed a data pipeline for Raleigh International to increase their data transparency",
  "Detonated 20 yottagrams of antimatter",
  "Developed a new data collection tool for Inlap to optimize their data collection",
  "Developed a solution to help JSI manage their data better.",
  "Devised a blueprint for counteracting the data fragmentation plaguing Expertise France",
  "Diaphanously illuminated 27 luminescent lissajous curves",
  "Discovered a new dimension of data visualization for OSF",
  "Discussed INL NOC document ",
  "Dismantled the labyrinth of interdependent data dependencies for Carter Center",
  "Dispatched the hydra of challenging code bugs.",
  "Dispelled the illusion of data discrepancies with IFDC.",
  "Dreamt up a data-driven solution for LMH to monitor their programs",
  "Elevated the data to new heights of accuracy and completeness for IAVI.",
  "Elevated the standard of data management for Counterpart.",
  "Elevated the state of data management with Restless Development.",
  "Emancipated 9 nanoseconds of temporal anomalies",
  "Emboldened the code to overcome the quagmire of data inefficiency for LMH.",
  "Empowered the Green Climate Fund to make data-driven decisions.",
  "Enabled direct data exports for World Renew by adding support for the OData protocol",
  "Encoded a software solution for counting data points for CRR.",
  "Encrypted the sensitive data of World Renew to ensure privacy and security",
  "Engaged with Guidehouse to build an advanced reporting system.",
  "Eradicated 17 instances of paradoxical taxonomy",
  "Escape more text in api endpoints",
  "Established a data governance framework for OpenDoors to ensure data quality",
  "Established a friendly partnership with CHISUProgram for custom data solutions.",
  "Evolved the data architecture for HT to optimize their reporting capabilities",
  "Excited 13 yottavolts of subatomic quasiparticles",
  "Exfoliated 15 nanoliters of epidermal cells",
  "Exorcised the demon of data duplication from Expertise France.",
  "Explored inclusive end date for RPs",
  "Explored the unknown territories of uncharted data sets",
  "Fabricated 19 decagrams of dolomite",
  "Fixed Accenture script",
  "Fixed data analysis scripts",
  "Fixed data analysis tools for improved accuracy",
  "Fixed X-axis spacing in dashboard tiles",
  "Fixed: App doesn't check localStorage for an existing rootDocId so it bootstraps a new root doc unless you have the hash in the URL",
  "Fixed: Attacker cannot use Undo API to undo privileged operations",
  "Flourished the fields of data growth with Heifer.",
  "Followed up on proposals (Mexico SURGES OAS Deliotte Digital Guidehouse)",
  "Fostered an alliance with Aba to improve their data management.",
  "Fought the good fight against the forces of tech debt",
  "Found out we didn't win the AASIT bid, but learned that we need to improve our proposal writing skills.",
  "Found out we didn't win the Project Hope bid, they decided to partner with another vendor",
  "Fueled the engine of innovation for Expertise France.",
  "Generated a wealth of custom data solutions for ChildFund.",
  "Had a delightful chat with Lab on modernizing their data management practices.",
  "Had a powerful dialogue with HRSM on improving their data collection processes.",
  "Had a productive call with GUIDEHOUSE to discuss potential future collaboration.",
  "Had a successful pitch with PMSPIRAQ on providing customized reporting tools.",
  "Had technical meeting with Aspiration ",
  "Harmonized the digital dichotomy of Green Climate Fund's data.",
  "Helped Carter Center conquer their data management challenges.",
  "Implemented a new feature for World Vision International to compare annual data trends",
  "Implemented a radiant system for counting data points for Global Water Partnership.",
  "Implemented custom data analysis techniques",
  "Implemented custom data visualization techniques",
  "Implemented more ATAP linkages",
  "Implemented new data visualization software",
  "Imported passwords into 1Password",
  "Incorporated a grand design for Advancing Nutrition's data analysis.",
  "Inculcated a cutting edge solution for Expertise France.",
  "IndicatorDefinition: allow data tables that don't have geography columns",
  "Infinitesimally regulated 45 aleph zero fluctuations",
  "Initiated 3 terawatts of megaparsec propulsion",
  "Innovated new solutions for ABT's data analysis challenges.",
  "Inoculated the network against 35 rogue algorithms",
  "Inscribed 18 platonic solids onto the event horizon",
  "Inscribed 21 hyperbolic logarithmic spirals",
  "Integrated more data into dashboard",
  "Integrated new data sources into analysis",
  "Integrated new data sources into reports",
  "Interpolated 42 nonlinear differential equations",
  "Juggled an array of complex data structures",
  "Learned React",
  "Lifted the curse of the broken data pipeline for GPE.",
  "Lost the bid for ChildFund, but received positive feedback for future opportunities",
  "Lost the bid for Counterpart, but received positive feedback for future opportunities",
  "Magnamimetically oscillated 63 gigacycle electromagnets",
  "Manifested an elegant and efficient solution for Global Communities.",
  "Mastered the art of creating beautiful, intuitive interfaces",
  "Masterminded a new system for managing project data for Heifer.",
  "Met with Advancing Nutrition and agreed to support their monitoring of food security indicators in real-time",
  "Met with CHISU Program and agreed to assist with data validation and cleaning for their maternal and child health indicators",
  "Met with Expertise France and agreed to optimize their data storage and retrieval for their agriculture programs",
  "Met with Global Water Partnership and agreed to help them improve the efficiency of their data analysis workflow",
  "Met with Guidehouse and discussed options for integrating their existing M&E tools into our platform",
  "Met with Proximity Designs and agreed to incorporate their feedback into improving the user experience for data entry",
  "Met with the Carter Center and discussed implementing advanced data visualization for their malaria program",
  "Met with the Episcopal Relief & Development and agreed to enhance their data management for disaster response programs",
  "Met with USAID and agreed to enhance their data security protocols for sensitive information",
  "Met with World Vision and decided to streamline their data collection processes using our custom forms feature",
  "Mitigated 16 terawatts of energy",
  "Navigated the maze of documentation with aplomb",
  "Negotiated a deal with ASASIT to extend their contract for an additional year with a 10% discount.",
  "Optimized 19 petaflops of quantum chromodynamics",
  "Optimized 42 nanoseconds of latency",
  "Optimized the database query for Plan to retrieve large datasets for their annual evaluations",
  "Optimized the production of 12 hyperdimensional matrices",
  "Orchestrated a flawless integration for Cordaid's data management.",
  "Organized a summit with 2SCALE to discuss data integration strategies.",
  "Ornamented the code with a beautiful solution for Plan.",
  "Pacified the chaos of data fragmentation with Durham University.",
  "Painted a masterpiece with the colors of CSS",
  "Patched a security vulnerability that affected Advance Nutrition's user account management",
  "Pioneered a breakthrough in data visualization for Corps Africa",
  "Planned local-first workshop",
  "Played a game of cat-and-mouse with the elusive bug",
  "Plenitudinously augmented 42 hyperdimensional hyperrealities",
  "Polarized 72 quasiperiodic fractals",
  "Prepped for Aspiration team meeting",
  "Presented demo for Aspiration",
  "Presented demos for Childblindness USAID",
  "Presented demos: OAS Mexico SURGES URC",
  "Promulgated a solution for counting data points for Corps Africa.",
  "Quantized 16 n dimensional manifold matrixes",
  "Quantized 17 exabytes of non-euclidean holography",
  "Quantized 25 petaflops of computational power",
  "Quantized 9 heptagonal dichroic lenses",
  "Rallied the data to new levels of accessibility and insight with Open Doors.",
  "Recalibrated 12 yottabytes of topological quantifiers",
  "Reconciled the differences between data and evaluation with USAID.",
  "Redeemed 20 lines of rogue code for ABT.",
  "Rematerialized 21 gigaparsecs of quasilinear superstrings",
  "Researched analytics options",
  "Researched and created new scripts for data analysis",
  "Researched and implemented new data analysis techniques",
  "Researched and implemented new data visualization techniques",
  "Researched data visualization software",
  "Researched dataelevates proposal",
  "Researched more into password managers",
  "Researched new data analysis techniques",
  "Researched new data sources for dashboard",
  "Researched new data visualization techniques",
  "Researched RFPs for 2023",
  "Researched SDR",
  "Resolved a 500 error that was preventing Abdool Karim from accessing the custom reports",
  "Resolved an issue with the map visualization for Raleigh International that was preventing them from mapping their projects.",
  "Resonated 8 gigahertz of tachyonic antiparticles",
  "Revamped of Data Table Access help page",
  "Reviewed 2022 contracts in process",
  "Reviewed contracts for pwc gec and syria art - both discontinuing due to project close",
  "Reviewed tenable scan",
  "Revolutionized the realm of data management with ChildFund.",
  "Rode the wave of cutting-edge technology",
  "Rode the wild stallion of technology to victory",
  "Sailed the seas of technical jargon with ChildFund.",
  "Secured a meeting with Heifer International to discuss potential partnership",
  "Set up ATAP linkage",
  "Signed contract with Advancing Nutrition for three years!!",
  "Signed contract with Caritas for one year ($120,000/yr)",
  "Signed contract with WINROCK for three years, with an annual budget of $180,000.",
  "Singled-handedly defeated the army of error messages",
  "Singularitized 57 black hole event horizons",
  "Soared to new heights with the soaring power of React",
  "Solved the Rubik's cube of complex queries",
  "Soothed the jagged edges of the ChildFund dashboard.",
  "Streamlined the data entry process for The Carter Center by integrating an API from the Ministry of Health",
  "Streamlined the data flow for Raleigh International.",
  "Subdued the dragon of data errors with World Learning.",
  "Submitted proposal to Green Climate Fund ($240,000/yr)",
  "Submitted proposal to LMH ($100,000/yr) detailing our services and the benefits they would receive.",
  "Submitted proposal to World Vision ($180,000/yr)",
  "Successfully closed the deal with NCA ($75,000/yr) after several rounds of negotiation.",
  "Successfully negotiated a higher budget with Cordaid ($450,000/yr)",
  "Surpassed the bounds of data limitations with Food the Children.",
  "Synchronized 17 chronometric chronometers",
  "Synchronized 57 millivolts of interstitial circuitry",
  "Tackled the thorny problem of data normalization",
  "Tamed the mischievous griffins of data manipulation",
  "Tangled with the knotty problem of spaghetti code",
  "Tranquilized the tempest of data disorganization for Expertise France.",
  "Transmogrified 27 hendecasyllabic lexemes",
  "Twisted and turned in a game of cat-and-mouse with the browser",
  "Undertook an epic journey with Plan on improving their data analysis capabilities.",
  "Unleashed a whirlwind of data-driven insights for Childfund",
  "Unleashed the power of the rainbow unicorn API",
  "Updated data visualization in reports",
  "Updated reporting dashboard",
  "Updated world shapes regions script",
  "Vanquished the evil race of missing semicolons.",
  "Won the bid for a two-year contract with World Renew",
  "Wrestled with the beast of the sprawling codebase",
  "Wrote a haiku about the harmony of code and design",
  "Wrote a love letter to the elegance of CSS",
  "Wrote a sonnet to the beauty of efficient algorithms",
  "Wrote an ode to the beauty of simple, clean code",
  "Wrote code-signed export script",
  "Wrote INL CIRT Log Query",
  "Wrote new custom query for XYA",
  "Wrote query & enterprise linkage for projects",
  "Wrote release note/comms for transfer of saved reports",
  "Wrote response for new shapefiles",
]
